/**
 * Orden de productos por categoría — auto-generado por npm run scrape:category-products
 * Fuente: https://www.tpharmagold.com (2026-06-15)
 */

export const CATEGORY_PRODUCT_SLUG_ORDERS: Record<string, readonly string[]> = {
  'premium': [
    'booty-abs-legs-for-woman',
    'abs-chest-legs-max-volume-for-men',
    'booty-abs-legs-for-woman-max',
    'tpower-precursor-de-testosterona',
    'boobs-hips',
    'mass-stack-for-women',
    'carni-cafit',
    'mass-stack-for-men',
    'chest-max-volume-super-pack',
    'pack-súper-reductor-glúteos-y-piernas-grandes',
    'pink-protein-para-mujeres-abs-booty-legs',
    'abs-chest-legs-max-cut-for-men',
    'pink-booty-boobs-kit',
    'extreme-pink-kit',
    'full-pack-hombre-súper-quemador',
    'pack-mujer-quemador',
    'abs-booty-legs-pink-protein',
    'abs-booty-legs-max-pink-protein',
    'chest-max-volume-protein',
  ],
  't-health': [
    'nocovir',
    'zinedol',
    'la-roja',
    'tirak',
    'sakax',
    'sakax-té',
    'tira-ft',
    'tpower-precursor-de-testosterona',
    'morigdes-protector-y-limpiador-hepático',
  ],
  'suplementos': [
    'i-want-yumbina',
    'i-want-enzimas-digestivas',
    'prework-cafe',
    'i-want-detox',
    'creatina-con-sabor',
    'i-want-curcuma-pimienta',
    'boobs-hips',
    'i-want-energy',
    'chest-max-volume-protein',
    'carni-cafit',
    'pink-pre-work-out',
    'pink-protein-para-mujeres-abs-booty-legs',
    'creatina-abs-legs-max',
    'l-glutamine-300-mg',
    'pink-bcaas-abs-booty-legs',
  ],
  'formulas-rendimiento': [
    'clomifin-gold-50',
    'tamox-gold-20',
    'anabol-gold',
    'clembu-gold',
    'anastro-gold',
    'trembo-gold',
    'stano-gold',
    'provi-gold',
    'primo-gold',
    'turina-gold-25',
    'oximet-gold',
    'oxa-gold',
  ],
  'vanguardia': [
    '3-cajas-de-stanozol',
    'stanozolo',
    'testo-cypionate',
    'testo-propionate',
    'methanolone-e',
    '4-test',
    'boldenone',
    'nondrolone',
    'drostanolone',
    'testo-enanthate',
    'trembolona-a',
  ],
  'moduladores': [
    'ibutamoren-max-mk-677',
    'max-s-23',
    'testolone-max-rad-140',
    'ligadrol-max-lgd-4033',
    'cardarine-max-gw-501516',
    'andarine-s4-max-s4',
    'stenabolic-max-sr9009',
    'myostatin-max-yk-11',
    'ostarine-max-mk2866',
  ],
  'factores-crecimiento': [
    'gentro-210-ui',
    'kingtropin-200ui',
    'jintropin-100ui',
    'somatrope-50ui',
    'zomacton15-ui',
    'norditropin40-ui',
  ],
}
